version: '3.5'

services:
  caddy:
    image: abiosoft/caddy:0.10.14
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile:cached
    ports:
      - 80:80
      - 443:443
    environment:
      - ACME_AGREE=true
    restart: always
  
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - 80
    volumes:
      - ./ui:/usr/src/app:cached
    command: /bin/sh -c "yarn install && npm run serve"

  engine:
    build: ./engine
    ports:
      - 3000:3000

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq:cached
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672

volumes:
  rabbitmq-data: null