version: '3.5'

services:
  caddy:
    image: abiosoft/caddy:0.10.14
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile:cached
    ports:
      - 80:80
      - 443:443
    environment:
      - ACME_AGREE=true
    restart: always
  
  ui:
    build: ./ui
    ports:
      - 80
    volumes:
      - ./ui:/usr/src/app:cached
    command: /bin/sh -c "yarn install && npm run serve"

  engine:
    build: ./engine
    env_file: ./engine/.env
    volumes:
      - ./engine:/usr/src/app:cached
    depends_on:
      - rabbitmq
  
  site:
    build: ./site
    command: ./bin/start.sh
    ports:
      - 4000:4000
    env_file: ./site/.env
    volumes:
      - ./site:/app:cached
    depends_on:
      - sitedb
      - rabbitmq
  
  sitedb:
    image: postgres:11.1
    volumes:
      - pg-data:/var/lib/postgresql/data:cached
    env_file: ./site/.env
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq:cached
    ports:
      - 5672:5672
      - 15672:15672
  
  docs:
    build: ./docs
    volumes:
      - ./docs:/docs:cached
    ports:
      - 8080:8080

volumes:
  rabbitmq-data: null
  pg-data: null
