site_name: KingdomGDocs
repo_url: https://github.com/gavr-games/kingdom-g/
nav:
    - Home: index.md
    - Site:
      - 'General': 'site/general.md'
      - 'API': 'site/api.md'
      - 'Arena Channel': 'site/arena_channel.md'
      - 'Base Channel': 'site/base_channel.md'
      - 'Game Channel': 'site/game_channel.md'
      - 'User Channel': 'site/user_channel.md'
      - 'Error Codes': 'site/error_codes.md'
      - 'Todo': 'site/todo.md'
    - RabbitMQ:
      - 'General': 'rabbitmq/general.md'
      - 'Game Management': 'rabbitmq/game_management_queue.md'
      - 'Game Actions': 'rabbitmq/game_actions.md'
      - 'Game Commands and Replies': 'rabbitmq/game_replies.md'
    - Engine:
      - 'Client JS Library': 'engine/client_api.md'
theme: readthedocs
dev_addr: '0.0.0.0:8080'
